/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejercicio;

import javax.swing.JOptionPane;

/**
 *
 * @author aolivero11
 */
public class Vectortres extends javax.swing.JFrame {

    /**
     * Creates new form Vectortres
     */
    double v[], v1[];
    public Vectortres() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtL1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtL2 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtRes = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        cmdCrear = new javax.swing.JButton();
        cmdLlenadoM = new javax.swing.JButton();
        cmdLlenadoAu = new javax.swing.JButton();
        cmdMostrar = new javax.swing.JButton();
        cmdBorrar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos iniciales:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 14))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Longitud 1:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        txtL1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtL1KeyTyped(evt);
            }
        });
        jPanel2.add(txtL1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 100, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Longitud 2:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        txtL2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtL2KeyTyped(evt);
            }
        });
        jPanel2.add(txtL2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 100, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 260, 120));

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Resultado:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 14))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtRes.setColumns(20);
        txtRes.setRows(5);
        jScrollPane1.setViewportView(txtRes);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 210, 150));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 250, 200));

        jPanel4.setBackground(new java.awt.Color(204, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Opciones:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 14))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmdCrear.setBackground(new java.awt.Color(255, 255, 204));
        cmdCrear.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmdCrear.setText("Crear");
        cmdCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCrearActionPerformed(evt);
            }
        });
        jPanel4.add(cmdCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 80, 30));

        cmdLlenadoM.setBackground(new java.awt.Color(255, 255, 204));
        cmdLlenadoM.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmdLlenadoM.setText("Llenado Manual");
        cmdLlenadoM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLlenadoMActionPerformed(evt);
            }
        });
        jPanel4.add(cmdLlenadoM, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 140, 30));

        cmdLlenadoAu.setBackground(new java.awt.Color(255, 255, 204));
        cmdLlenadoAu.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmdLlenadoAu.setText("Llenado Automatico");
        cmdLlenadoAu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLlenadoAuActionPerformed(evt);
            }
        });
        jPanel4.add(cmdLlenadoAu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 170, 30));

        cmdMostrar.setBackground(new java.awt.Color(255, 255, 204));
        cmdMostrar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmdMostrar.setText("Mostrar");
        cmdMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdMostrarActionPerformed(evt);
            }
        });
        jPanel4.add(cmdMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 80, 30));

        cmdBorrar.setBackground(new java.awt.Color(255, 255, 204));
        cmdBorrar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmdBorrar.setText("Borrar");
        cmdBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBorrarActionPerformed(evt);
            }
        });
        jPanel4.add(cmdBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 80, 30));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 220, 250));

        jLabel3.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 0, 102));
        jLabel3.setText("    OPERACIONES");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 190, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 571, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCrearActionPerformed
        int l, l2;
       if (txtL1.getText().trim().isEmpty()){
           JOptionPane.showMessageDialog(this, "Digite la longitud","Error",JOptionPane.ERROR_MESSAGE);
           txtL1.requestFocusInWindow();
       }
       else if(txtL2.getText().trim().isEmpty()){
        JOptionPane.showMessageDialog(this, "Digite la longitud", "Error",JOptionPane.ERROR_MESSAGE);
        txtL2.requestFocusInWindow();
       }
       else if (Integer.parseInt(txtL1.getText().trim())==0){
         JOptionPane.showMessageDialog(this, "No digite cero en la longitud","Error",JOptionPane.ERROR_MESSAGE);
         txtL1.requestFocusInWindow();
         txtL1.selectAll();
       }
       else if (Integer.parseInt(txtL2.getText().trim())==0){
         JOptionPane.showMessageDialog(this, "No digite cero en la longitud","Error",JOptionPane.ERROR_MESSAGE);
         txtL2.requestFocusInWindow();
         txtL2.selectAll(); 
       }
       else{
           l=Integer.parseInt(txtL1.getText().trim());
           v = new double [l];
           JOptionPane.showMessageDialog(this, "Vector creado exitosamente!");
           
           l2=Integer.parseInt(txtL2.getText().trim());
           v1 = new double [l2];
           JOptionPane.showMessageDialog(this, "Vector dos creado exitosamente!");
       }
    }//GEN-LAST:event_cmdCrearActionPerformed

    private void cmdLlenadoMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLlenadoMActionPerformed
       double n;
        for (int i = 0; i < v.length; i++) {
            n=Double.parseDouble(JOptionPane.showInputDialog("Digite el elemento en la posicion" +i));
            v[i]=n;
        }
        for (int i = 0; i < v.length; i++) {
          n=Double.parseDouble(JOptionPane.showInputDialog("Digite el elemento en la posicion" +i));
            v1[i]=n;  
            
        }
    }//GEN-LAST:event_cmdLlenadoMActionPerformed

    private void cmdLlenadoAuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLlenadoAuActionPerformed
       double n;
        for (int i = 0; i < v.length; i++) {
            n=(int)(Math.random()* + 1);
            n=i+1;
            v[i]=1;
        }
    }//GEN-LAST:event_cmdLlenadoAuActionPerformed

    private void cmdMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdMostrarActionPerformed
        double suma,resta;
        for (int i = 0; i < v.length; i++) {
          txtRes.append(v[i]+ "\n");
        }
        for (int i = 0; i < v.length; i++) {
          txtRes.append(v1[i]+"\n");
        }
        for (int i = 0; i < v.length; i++) {
            suma=v[i]+v1[i];
        JOptionPane.showMessageDialog(this,"La suma del vector 1 y vector 2 es:" +suma); 
            
        }
        for (int i = 0; i <v.length; i++) {
            resta=v[i]-v1[i];
           JOptionPane.showMessageDialog(this,"La resta del vector 1 y vector 2 es:" +resta); 
        }
       
    }//GEN-LAST:event_cmdMostrarActionPerformed

    private void cmdBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBorrarActionPerformed
       txtL1.setText("");
        txtL2.setText("");
        txtRes.setText("");
        v = null;
        v1 = null;
        txtL1.requestFocusInWindow();
        txtL2.requestFocusInWindow();
    }//GEN-LAST:event_cmdBorrarActionPerformed

    private void txtL1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtL1KeyTyped
        char c=evt.getKeyChar(); 

          if(!Character.isDigit(c)) { 
              getToolkit().beep(); 
               
              evt.consume();  
          }
    }//GEN-LAST:event_txtL1KeyTyped

    private void txtL2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtL2KeyTyped
        char c=evt.getKeyChar(); 

          if(!Character.isDigit(c)) { 
              getToolkit().beep(); 
               
              evt.consume();  
          }
    }//GEN-LAST:event_txtL2KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vectortres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vectortres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vectortres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vectortres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vectortres().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdBorrar;
    private javax.swing.JButton cmdCrear;
    private javax.swing.JButton cmdLlenadoAu;
    private javax.swing.JButton cmdLlenadoM;
    private javax.swing.JButton cmdMostrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtL1;
    private javax.swing.JTextField txtL2;
    private javax.swing.JTextArea txtRes;
    // End of variables declaration//GEN-END:variables
}
